# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giaodien_yolo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 771, 501))
        self.label.setText("")
        self.label.setObjectName("label")
        self.chon_duong_dan_bt = QtWidgets.QPushButton(self.centralwidget)
        self.chon_duong_dan_bt.setGeometry(QtCore.QRect(170, 8, 75, 23))
        self.chon_duong_dan_bt.setObjectName("chon_duong_dan_bt")
        self.browser_path_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.browser_path_txt.setGeometry(QtCore.QRect(10, 10, 151, 20))
        self.browser_path_txt.setObjectName("browser_path_txt")
        self.chon_duong_dan_bt_2 = QtWidgets.QPushButton(self.centralwidget)
        self.chon_duong_dan_bt_2.setGeometry(QtCore.QRect(250, 8, 75, 23))
        self.chon_duong_dan_bt_2.setObjectName("chon_duong_dan_bt_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 12, 47, 13))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chon_duong_dan_bt.setText(_translate("MainWindow", "Browse"))
        self.chon_duong_dan_bt_2.setText(_translate("MainWindow", "Detect"))
        self.label_2.setText(_translate("MainWindow", "Result:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
